name: Deploy to EC2 From GitHub Actions

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          sudo pip3 install virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
      - name: Deploy Code
        run: |
          ssh -i ${{ secrets.aws_ec2_ssh_key_mac }} ubuntu@3-110-32-195
          echo "Completed connecting via ssh"
          
          cd /home/ubuntu/testing-django
          echo "Inside Project folder"
          
          git pull 
          echo "Git Pull completed"
          
          source env/bin/activate
          echo "Environment activated"
          
          pip install -r requirements.txt
          echo "installed requirements"
          
          sudo systemctl restart test-django.service"
          echo "restarting service"
